### ISSUE TITLE
Add build instructions

### ISSUE THREAD

**Issue by t0stiman** [diamondburned/gtkcord4#1]
Some compilation instructions and a list of requirements would be most welcome.

**Comment by KorbsStudio** [comment]
YES PLS

**Comment by sylviiu** [comment]
I'm not sure if this is the OFFICIAL way to go about it, but...

gtkcord3's installation process invoked one command: `go install -v github.com/diamondburned/gtkcord3@latest`

having no knowledge of go, i *assumed* that it pulled the files from the repository & builds according to the instructions for go in the git repo; i replaced the old URL with this repository's URL (`go install -v github.com/diamondburned/gtkcord4@latest`) and the process actually started! it's still downloading at the time of writing this, so i'll edit the message if it works

**Comment by Animationss** [comment]
Hmm....
`github.com/diamondburned/gotk4/pkg/gtk/v4
^[[1;2C^[[1;4C^[[1;4C^[^]^[?^[>^\SIGQUIT: quit
PC=0x467101 m=0 sigcode=128

goroutine 0 [idle]:
runtime.futex()
	/usr/lib/go-1.17/src/runtime/sys_linux_amd64.s:519 +0x21
runtime.futexsleep(0xc00003a800, 0x3676dc00, 0x0)
	/usr/lib/go-1.17/src/runtime/os_linux.go:44 +0x36
runtime.notesleep(0xd8b8f0)
	/usr/lib/go-1.17/src/runtime/lock_futex.go:160 +0x87
runtime.mPark()
	/usr/lib/go-1.17/src/runtime/proc.go:1441 +0x2a
runtime.stopm()
	/usr/lib/go-1.17/src/runtime/proc.go:2408 +0x78
runtime.findrunnable()
	/usr/lib/go-1.17/src/runtime/proc.go:2984 +0x865
runtime.schedule()
	/usr/lib/go-1.17/src/runtime/proc.go:3367 +0x239
runtime.park_m(0xc000301ba0)
	/usr/lib/go-1.17/src/runtime/proc.go:3516 +0x14d
runtime.mcall()
	/usr/lib/go-1.17/src/runtime/asm_amd64.s:307 +0x43

goroutine 1 [semacquire, 24 minutes]:
sync.runtime_Semacquire(0x0)
	/usr/lib/go-1.17/src/runtime/sema.go:56 +0x25
sync.(*WaitGroup).Wait(0x93ed00)
	/usr/lib/go-1.17/src/sync/waitgroup.go:130 +0x71
cmd/go/internal/work.(*Builder).Do(0xc000bd5360, {0xa6f480, 0xc0000240d0}, 0xc000596140)
	/usr/lib/go-1.17/src/cmd/go/internal/work/exec.go:208 +0x4b5
cmd/go/internal/work.InstallPackages({0xa6f480, 0xc0000240d0}, {0xc000d5f110, 0xc0000200b0, 0x1}, {0xc0009f8248, 0x1, 0x1})
	/usr/lib/go-1.17/src/cmd/go/internal/work/build.go:720 +0xa87
cmd/go/internal/work.installOutsideModule({0xa6f480, 0xc0000240d0}, {0xc0000200b0, 0x1, 0x1})
	/usr/lib/go-1.17/src/cmd/go/internal/work/build.go:781 +0x198
cmd/go/internal/work.runInstall({0xa6f480, 0xc0000240d0}, 0xc000028570, {0xc0000200b0, 0x1, 0x1})
	/usr/lib/go-1.17/src/cmd/go/internal/work/build.go:585 +0x512
main.invoke(0xd7f5a0, {0xc000020090, 0x3, 0x3})
	/usr/lib/go-1.17/src/cmd/go/main.go:216 +0x2f6
main.main()
	/usr/lib/go-1.17/src/cmd/go/main.go:173 +0x78e

goroutine 1740 [syscall]:
syscall.Syscall6(0xf7, 0x1, 0x10632, 0xc000092a60, 0x1000004, 0x0, 0x0)
	/usr/lib/go-1.17/src/syscall/asm_linux_amd64.s:43 +0x5
os.(*Process).blockUntilWaitable(0xc00002ac30)
	/usr/lib/go-1.17/src/os/wait_waitid.go:33 +0x9c
os.(*Process).wait(0xc00002ac30)
	/usr/lib/go-1.17/src/os/exec_unix.go:23 +0x28
os.(*Process).Wait(...)
	/usr/lib/go-1.17/src/os/exec.go:132
os/exec.(*Cmd).Wait(0xc000232b00)
	/usr/lib/go-1.17/src/os/exec/exec.go:507 +0x54
os/exec.(*Cmd).Run(0x8f8d60)
	/usr/lib/go-1.17/src/os/exec/exec.go:341 +0x39
cmd/go/internal/work.(*Builder).runOut(0xc000164480, 0xc00081d400, {0xc000533490, 0x10000c000092e50}, {0xc000c36240, 0x2, 0x18}, {0xc000093348, 0xb, 0xb})
	/usr/lib/go-1.17/src/cmd/go/internal/work/exec.go:2103 +0x5cf
cmd/go/internal/work.(*Builder).run(0xc000214000, 0xa, {0xc000533490, 0x62}, {0xc0002db3e1, 0x29}, {0xc000c36240, 0x529169, 0xc000093030}, {0xc000093348, ...})
	/usr/lib/go-1.17/src/cmd/go/internal/work/exec.go:2015 +0x92
cmd/go/internal/work.(*Builder).cgo(0x40ea07, 0xc00081d400, {0xc0006a0e70, 0x29}, {0xc00030dec0, 0x580605}, {0xc0001c4200, 0x1a, 0x0}, {0xc000399080, ...}, ...)
	/usr/lib/go-1.17/src/cmd/go/internal/work/exec.go:2807 +0x18f5
cmd/go/internal/work.(*Builder).build(0xc000bd5360, {0xc0000240d0, 0x0}, 0xc00081d400)
	/usr/lib/go-1.17/src/cmd/go/internal/work/exec.go:676 +0x4031
cmd/go/internal/work.(*Builder).Do.func2({0xa6f480, 0xc0000240d0}, 0xc00081d400)
	/usr/lib/go-1.17/src/cmd/go/internal/work/exec.go:137 +0x5ec
cmd/go/internal/work.(*Builder).Do.func3()
	/usr/lib/go-1.17/src/cmd/go/internal/work/exec.go:199 +0xb9
created by cmd/go/internal/work.(*Builder).Do
	/usr/lib/go-1.17/src/cmd/go/internal/work/exec.go:185 +0x3df

goroutine 1741 [select]:
cmd/go/internal/work.(*Builder).Do.func3()
	/usr/lib/go-1.17/src/cmd/go/internal/work/exec.go:189 +0x112
created by cmd/go/internal/work.(*Builder).Do
	/usr/lib/go-1.17/src/cmd/go/internal/work/exec.go:185 +0x3df

goroutine 2321 [runnable]:
syscall.Syscall(0x0, 0x7, 0xc00032ba00, 0x400)
	/usr/lib/go-1.17/src/syscall/asm_linux_amd64.s:20 +0x5
syscall.read(0xc00087f140, {0xc00032ba00, 0x44bb01, 0x5018be})
	/usr/lib/go-1.17/src/syscall/zsyscall_linux_amd64.go:687 +0x4d
syscall.Read(...)
	/usr/lib/go-1.17/src/syscall/syscall_unix.go:189
internal/poll.ignoringEINTRIO(...)
	/usr/lib/go-1.17/src/internal/poll/fd_unix.go:582
internal/poll.(*FD).Read(0xc00087f140, {0xc00032ba00, 0x400, 0x400})
	/usr/lib/go-1.17/src/internal/poll/fd_unix.go:163 +0x285
os.(*File).read(...)
	/usr/lib/go-1.17/src/os/file_posix.go:32
os.(*File).Read(0xc000a18540, {0xc00032ba00, 0x7f9b0db9ca18, 0xc0007ceea0})
	/usr/lib/go-1.17/src/os/file.go:119 +0x5e
bytes.(*Buffer).ReadFrom(0xc000c205d0, {0xa62d00, 0xc000a18540})
	/usr/lib/go-1.17/src/bytes/buffer.go:204 +0x98
io.copyBuffer({0xa61e20, 0xc000c205d0}, {0xa62d00, 0xc000a18540}, {0x0, 0x0, 0x0})
	/usr/lib/go-1.17/src/io/io.go:409 +0x14b
io.Copy(...)
	/usr/lib/go-1.17/src/io/io.go:382
os/exec.(*Cmd).writerDescriptor.func1()
	/usr/lib/go-1.17/src/os/exec/exec.go:311 +0x3a
os/exec.(*Cmd).Start.func1(0x0)
	/usr/lib/go-1.17/src/os/exec/exec.go:441 +0x25
created by os/exec.(*Cmd).Start
	/usr/lib/go-1.17/src/os/exec/exec.go:440 +0x80d

rax    0xca
rbx    0x0
rcx    0x467103
rdx    0x0
rdi    0xd8b8f0
rsi    0x80
rbp    0x7fff7a057b48
rsp    0x7fff7a057b00
r8     0x0
r9     0x0
r10    0x0
r11    0x286
r12    0x4d0
r13    0x0
r14    0xd8ab60
r15    0xffffffffffffffff
rip    0x467101
rflags 0x286
cs     0x33
fs     0x0
gs     0x0
`

No clue what happened

**Comment by Animationss** [comment]
Hmmm...

https://pastebin.com/vQXHV2yF

No clue what happened here...

**Comment by poudink** [comment]
it's the exact same as gtkcord3. go install -v github.com/diamondburned/gtkcord3@[commit]. 
@Animationss I think you might be missing the gtk4 build dependency.

**Comment by diamondburned** [comment]
> https://pastebin.com/vQXHV2yF

This is just the compiler being slow. You can wait out for the whole build or you can patch the compiler to make it faster. See https://github.com/golang/go/issues/9887#issuecomment-913056050 for more information.

**Comment by diamondburned** [comment]
> I'm not sure if this is the OFFICIAL way to go about it, but...
> 
> gtkcord3's installation process invoked one command: `go install -v github.com/diamondburned/gtkcord3@latest`

This is indeed what I'll eventually add onto the README. You can also clone the repository down and run `go install` within, but this works just fine.

I'll also eventually add a CI that automatically produces binaries for each release, but that's only for when I'm happy with the state of the program.

**Comment by AldairbotHerotaku** [comment]
> > I'm not sure if this is the OFFICIAL way to go about it, but...
> > gtkcord3's installation process invoked one command: `go install -v github.com/diamondburned/gtkcord3@latest`
> 
> This is indeed what I'll eventually add onto the README. You can also clone the repository down and run `go install` within, but this works just fine.
> 
> I'll also eventually add a CI that automatically produces binaries for each release, but that's only for when I'm happy with the state of the program.
> 
> > having no knowledge of go, i assumed that it pulled the files from the repository & builds according to the instructions for go in the git repo
> 
> There is actually no custom way to build this project. Most Go projects build the same, and the toolchain handles all the complicated steps. The only additional step here is installing the C dependencies of the program.

your fork of go is super fast for the build, It take 8 sec to build

**Comment by diamondburned** [comment]
> your fork of go is super fast, It take 8 sec to build

This might just be because you've already built it before, so the time-intensive parts (gotk4) are cached. It will be cached until you update your Go version or I update the dependencies.

**Comment by AldairbotHerotaku** [comment]
> 
No, the difference is 7 sec to 8 min with the other GO version under the same conditions

**Comment by BasicNoob** [comment]
> > https://pastebin.com/vQXHV2yF
> 
> This is just the compiler being slow. You can wait out for the whole build or you can patch the compiler to make it faster. See [golang/go#9887 (comment)](https://github.com/golang/go/issues/9887#issuecomment-913056050) for more information.

Dont see any proper way to install this?

**Comment by diamondburned** [comment]
> Dont see any proper way to install your fork of go?

There's no "proper way" to install it. It patches over the source code, so use whichever way to do that that your distro recommends.

The way I do it is with a Nix overlay, as written in the bottom comment, but that's only for me (and Nix users).

**Comment by TheKrafter** [comment]
[I get errors regarding pkg-config when building](https://pastebin.com/XytZqSR4)
This happens both on Pop!_OS 21.10 (amd64), and on Mobian (aarch64). 
I don't think I've changed or used pkg-config for anything else since install. It appears that I'm missing some packages:
gobject-introspection-1.0, cairo, cairo-gobject, graphene-gobject-1.0, and graphene-1.0 
any ideas of what these packages would be called in the default repos?
I don't build things very often, especially with go. So any help would be appreciated. It might be debian-specific, I'll test on my fedora machine later today.

**Comment by diamondburned** [comment]
> any ideas of what these packages would be called in the default repos?

Try [these](https://github.com/diamondburned/gotk4-examples#linux---ubuntu).

**Comment by BasicNoob** [comment]
> > Dont see any proper way to install your fork of go?
> 
> There's no "proper way" to install it. It patches over the source code, so use whichever way to do that that your distro recommends.
> 
> The way I do it is with a Nix overlay, as written in the bottom comment, but that's only for me (and Nix users).

Noticed Pop os is like the worst distro to build stuff on, Atleast for coding noobs like me. So how would I apply this patch on pop os 21.10

**Comment by poudink** [comment]
the nix package manager should be available on any linux distro

**Comment by metalune1** [comment]
so is there any particular reason why you wouldn't include the `go install -v github.com/diamondburned/gtkcord4@latest` on the README.md right now?

**Comment by diamondburned** [comment]
> so is there any particular reason why you wouldn't include the `go install -v github.com/diamondburned/gtkcord4@latest` on the README.md right now?

It isn't yet a priority to me.

**Comment by metalune1** [comment]
So if I were to send a PR with those Instructions added you would merge it?

**Comment by diamondburned** [comment]
> So if I were to send a PR with those Instructions added you would merge it?

Yes.

**Comment by diamondburned** [comment]
Closed by https://github.com/diamondburned/gtkcord4/pull/6.
