### ISSUE TITLE
Build error for user on AUR

### ISSUE THREAD

**Issue by txtsd** [diamondburned/gtkcord4#10]
https://aur.archlinux.org/packages/gtkcord4-git#comment-862101

Here's a link to the comment. It says

```
I'm having a weird build issue with this. Whenever I try to install the package, it fails to build and gives me this message:

Package gobject-introspection-1.0 was not found in the pkg-config search path. Perhaps you should add the directory containing `gobject-introspection-1.0.pc' to the PKG_CONFIG_PATH environment variable Package 'gobject-introspection-1.0', required by 'virtual:world', not found pkg-config: exit status 1

I dunno if this is a dependency issue or what.
```

**Comment by diamondburned** [comment]
It is a dependency. See https://github.com/diamondburned/gtkcord4/issues/8.

**Comment by txtsd** [comment]
Is it a build dependency or a runtime dependency?

**Comment by diamondburned** [comment]
It's both a build-time dependency and a runtime dependency. `gobject-introspection` supplies GLib type functions like `g_X_get_type()`.

**Comment by txtsd** [comment]
Thanks. I'll add it to the dependencies.
