### ISSUE TITLE
gtkcord4 on AUR doesn't have a libadwaita binary variant

### ISSUE THREAD

**Issue by diamondburned** [diamondburned/gtkcord4#109]
cc @txtsd 

Can we have an AUR package for gtkcord4-libadwaita-bin? This is more for my friend, but I figured it should be consistent with the two `-git` packages.

A new release v0.0.9 could be drafted if needed.

**Comment by txtsd** [comment]
I can get on it in a few hours, no problemo. I was already thinking about it last night.

A 0.9.0 would be nice with the fix for permissions.

**Comment by txtsd** [comment]
Okay!
