### ISSUE TITLE
Idiot proofing the how to build the Libadwaita variant on README

### ISSUE THREAD

**Issue by nesper8** [diamondburned/gtkcord4#111]
For context 
I am someone who has little to no experience with programming let alone go so it kinda made me dumbfounded when i tried to make the libadwaita variant by running `go install -tags libadwaita` which didnt work obviously

then i tried passing the tags flag on to the quick build command which shown this error
```
go install github.com/diamondburned/gtkcord4@latest -tags libadwaita 
go: -tags: all arguments must refer to packages in the same module at the same version (@latest)
```

so it would be cool if you could idiot proof the README a bit more
Thank you very much in advance

**Comment by diamondburned** [comment]
`go install -tags libadwaita github.com/diamondburned/gtkcord4@latest` should work. In the future, the libadwaita build might become the default build, so no tags would be needed then.

**Comment by nesper8** [comment]
Thank you very much 
I'll close the issue now

**Comment by nesper8** [comment]
I'm getting this error when i tried to build with the command above
```
# pkg-config --cflags  -- libadwaita-1
Package libadwaita-1 was not found in the pkg-config search path.
Perhaps you should add the directory containing `libadwaita-1.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libadwaita-1' found
pkg-config: exit status 1
```

**Comment by nesper8** [comment]
Closing
I'm an idiot

**Comment by UInt2048** [comment]
When I'm an idiot in the future, install `libadwaita-1-dev` if I get that error
