### ISSUE TITLE
Option to disable `Redacted`

### ISSUE THREAD

**Issue by Ecorous** [diamondburned/gtkcord4#114]
On deleted messages, gtkcord shows `Redacted` instead of removing the message from chat. This annoying when used in combination with bots such as [PluralKit](https://pluralkit.me). Can a way to disable this be added to preferences?

**Comment by diamondburned** [comment]
This is more because of laziness than an actual preference. I didn't want to figure out a good way to reformat the above message when the message underneath it was deleted as I did with gtkcord3.

I can probably get to it, I think.

**Comment by Ecorous** [comment]
Hi! Is there any update on this?

**Comment by diamondburned** [comment]
This has now been implemented as part of 9ad2c7145cd3df432e1b7a03681f305d620cb80a. The redact setting is now off by default:

![image](https://github.com/diamondburned/gtkcord4/assets/8463786/b109de0b-f6ff-4c64-b327-6b4654026c05)
