### ISSUE TITLE
Some channels are invisible

### ISSUE THREAD

**Issue by UltraBlackLinux** [diamondburned/gtkcord4#115]
Hey there,
for about a week I struggled to find the announcements channel on the hyprland discord. Pings would go through but the channel was just nowhere to be found in gtkcord. This seems to be the same for many other discord servers. Maybe there are even more missing channels 

Could you fix this?
Thanks!

**Comment by diamondburned** [comment]
Do you know what the channel type for it is? gtkcord4 ignores channels that it doesn't know for sure how to handle; that channel's type might not be on that list.

**Comment by UltraBlackLinux** [comment]
In Hyperland's case it's a followable channel.

**Comment by diamondburned** [comment]
I'm not sure what [channel type](https://discord.com/developers/docs/resources/channel#channel-object-channel-types) that is. FWIW, gtkcord4 should support announcement/news channels, which are followable.

**Comment by UltraBlackLinux** [comment]
I can't find this in the debugger, maybe you can give it a shot? I don't know which one it could be

**Comment by asdfghjkl403622** [comment]
can confirm, anytime I get pinged from any channel, I have to go to my desktop to see wassup

**Comment by TheKrafter** [comment]
to clarify, its `GUILD_ANNOUNCEMENT`, id `5` (as per [the docs](https://discord.com/developers/docs/resources/channel#channel-object-channel-types))

**Comment by diamondburned** [comment]
Maybe commit f73790aa413d4b4b0dee9398ece835b92c075cd7 fixes this.

**Comment by UInt2048** [comment]
@diamondburned Thank you. I can see the announcement channel now using the nightly.

You can install it like this: `go install -v github.com/diamondburned/gtkcord4@nightly`
