### ISSUE TITLE
Windows version

### ISSUE THREAD

**Issue by Detector-I** [diamondburned/gtkcord4#12]
Hi, any plan for windows version?
or is it possible at all?

**Comment by diamondburned** [comment]
It is possible; gtkcord4 should work out of the box on Windows, macOS and Linux. You will need to build it yourself on both Windows and macOS, however. I only provide prebuilt binaries for Linux x86_64 and aarch64.

**Comment by diamondburned** [comment]
I closed the issue because it's question answered, but others are free to use this issue to discuss how to set up a Windows compiling environment. I personally prefer using msys.

**Comment by Detector-I** [comment]
> I closed the issue because it's question answered, but others are free to use this issue to discuss how to set up a Windows compiling environment. I personally prefer using msys.

thank you for answer, in install it give me this error
```
# pkg-config --cflags  -- glib-2.0 gobject-introspection-1.0
Can't find gobject-introspection-1.0.pc in any of G:/gnome/lib/pkgconfig C:/Strawberry/c/lib/pkgconfig
use the PKG_CONFIG_PATH environment variable, or
specify extra search paths via 'search_paths'
pkg-config: exit status 1
```
should I build the gobject-introspection too?
and also, does using it totally safe?

**Comment by diamondburned** [comment]
> should I build the gobject-introspection too?

You install it using msys' package manager (`pacman`).

> and also, does using it totally safe?

Who knows, and I'm in no position to claim that it is. Use it at your own risk.

**Comment by Detector-I** [comment]
> > should I build the gobject-introspection too?
> 
> You install it using msys' package manager (`pacman`).
> 
> > and also, does using it totally safe?
> 
> Who knows, and I'm in no position to claim that it is. Use it at your own risk.

well I did use msys2, and used pacman to install gtk4... 
but now in build it give me
```
G:\msys64\mingw64\lib\go\pkg\tool\windows_amd64\link.exe: running gcc failed: fork/exec G:\msys64\mingw64\bin\gcc.exe: The filename or extension is too long.
```
not sure how can I fix it...

**Comment by diamondburned** [comment]
Try https://github.com/diamondburned/gotk4/issues/64#issuecomment-1104889379.

**Comment by Detector-I** [comment]
> Try [diamondburned/gotk4#64 (comment)](https://github.com/diamondburned/gotk4/issues/64#issuecomment-1104889379).

ok managed to build it (I had to change temp directory in env variable settings to get it to work)
but now looks like it can't find the needed styles... what should I do now?
![image](https://user-images.githubusercontent.com/18105381/165505532-f163d34f-e801-44f9-abdc-e10afed53457.png)

**Comment by diamondburned** [comment]
That is not "needed." The program is working as intended.

**Comment by Detector-I** [comment]
> That is not "needed." The program is working as intended.

I know the program work without style, but screen shot in readme looks way better, so Im trying to get that...

**Comment by diamondburned** [comment]
> I know the program work without style, but screen shot in readme looks way better, so Im trying to get that...

The screenshot uses the Materia theme, which is a system-wide theme. You'll need to download that separately.

`user.css` is mostly for user customizations.

**Comment by Katzenwerfer** [comment]
Hi,
I'm trying to build the program using MSYS2 on Windows 11. I'm pretty sure I got all the packages installed and stuff, but when I run `go install` it throws me various `#error Only Win32 target is supported!` errors.
Anyone knows what could be the cause of that?

**Comment by brian6932** [comment]
@diamondburned I tried building for Windows, and despite having all requirements, ran into an error where the include files were not found, do you know why this would happen?
![image](https://user-images.githubusercontent.com/18603393/188538047-07c88481-296f-4108-ba14-e107a8a09389.png)

**Comment by diamondburned** [comment]
I'm not sure. I've only really tested this on Windows 10 MSYS2.

**Comment by brian6932** [comment]
@diamondburned I am using msys2 on Windows 10 for my pkg-config
![image](https://user-images.githubusercontent.com/18603393/188619832-219c4fd0-6e82-4657-b370-7b11991be31f.png)

**Comment by brian6932** [comment]
Ok I managed to get the paths included, I had to set `CGO_CFLAGS` manually, because go was not converting the unix msys2 pkg-config paths to Windows ones,
