### ISSUE TITLE
Safe to use?

### ISSUE THREAD

**Issue by OverloaderV** [diamondburned/gtkcord4#120]
Before i use this: how safe is it? are there known bans of people using this?

**Comment by diamondburned** [comment]
Not that I know of. I'm not taking any responsibility if anyone does get banned, though. Use at your own risk.

**Comment by algj** [comment]
https://news.ycombinator.com/item?id=39762890
https://news.ycombinator.com/item?id=28438440

There was a conversation regarding this. Seems like Discord devs don't actually want to ban third party client users, though they do target spam-bots.
