### ISSUE TITLE
Read voice channel chats

### ISSUE THREAD

**Issue by TheKrafter** [diamondburned/gtkcord4#123]
As voice channels have chats in them, allow us to read them as normal channels. Currently, they're marked as unread even if we cant see the messages.

**Comment by diamondburned** [comment]
Have you tried the latest pre-release? It should contain commit https://github.com/diamondburned/gtkcord4/commit/47cb77d02d93334fc806a478a6a64fdb6d501037 (the latest commit) which has this change.

**Comment by UInt2048** [comment]
@TheKrafter Try installing the nightly like this:

`go install -v github.com/diamondburned/gtkcord4@nightly`
