### ISSUE TITLE
Plugin Clients on gtkcord4?

### ISSUE THREAD

**Issue by masakk1** [diamondburned/gtkcord4#124]
I use some plugins with Vencord but I was wondering if these would work for gtkcord4.

I doubt it since it probably searches for objects that do not exist since it uses another interface. I'm not asking for themes by the way, there would be no point to use themes with this since it will already use mine.

If no one knows, I could try doing some tests myself.
- Mas

**Comment by masakk1** [comment]
yeah after some digging and testing i realised it's pretty much impossible. It'd be cool if plugins could be made though...

**Comment by diamondburned** [comment]
Plugins support could definitely be added in the future, but it wouldn't be simple. Go isn't an interpreted language, so some effort has to be made to expose the underlying Go functions to a different scripting language.

**Comment by masakk1** [comment]
Speaking of GO, I've never seen the Go language to build gtk applications.

On their website they got some languages like C, python, vals... But I did not see go there.

Is it an unofficial port? I don't really use go so I don't know if I'm missing something.

**Comment by diamondburned** [comment]
I made [the bindings generator](https://github.com/diamondburned/gotk4). Unofficial, I suppose. It is [in the official GTK language bindings table](https://www.gtk.org/docs/language-bindings/index), if that means anything.
