### ISSUE TITLE
Chat history not updated when scrolling

### ISSUE THREAD

**Issue by UltraBlackLinux** [diamondburned/gtkcord4#128]
Hey there,
gtkcord seems to lack the ability to add older chat messages to the chat history when scrolling upwards. It often leaves me stumped about what happened.
Could you fix that?
Thanks!

**Comment by hmenke** [comment]
Possible duplicate of https://github.com/diamondburned/gtkcord4/issues/86?

**Comment by UltraBlackLinux** [comment]
oh it's not even a bug? Just not implemented? Well, github search didn't help yet again.

Thanks, will close.,
