### ISSUE TITLE
Voice Chat?

### ISSUE THREAD

**Issue by BasicNoob** [diamondburned/gtkcord4#13]
Finally got Gtkcord4 installed thanks to the binary, Its fine as it is (besides the missing servers) but I noticed there where no voice. Will you be adding them in a future update or...?

**Comment by diamondburned** [comment]
I won't add voice chat. It's too complicated, barely documented, and is overall a pain to work with. If I ever do, I'll put it in a separate client.

**Comment by ThatOneCalculator** [comment]
Please reconsider this :(

**Comment by asparkswghs** [comment]
@ThatOneCalculator if you want voice chat that badly, try implementing it yourself! This is open source we're talking about

**Comment by ThatOneCalculator** [comment]
I barely know Golang, I don't know anything about WebRTC and I also have other projects (as well as work + school) to worry about. Open Source ≠ DIY
