### ISSUE TITLE
[Feature Request] Add Light Theme

### ISSUE THREAD

**Issue by jan-sonki** [diamondburned/gtkcord4#130]
Currently, gtkcord4 only has a dark theme available. This issue proposes the addition of a light theme to provide users with more customization options and improve the overall user experience. Here are some reasons why a light theme should be added:

User preference: Some users may prefer a lighter theme for various reasons, such as personal taste or accessibility needs.
Consistency with other applications: Most other GTK4 applications offer both light and dark themes, allowing users to choose the one that best suits their preferences and system settings.
Accessibility: A light theme can improve readability and accessibility for users with certain visual impairments or those who have difficulty reading text on dark backgrounds.

For the settings UI to switch between light and dark themes in gtkcord4, it would be better to place the option inside the Preferences menu, as this is more consistent with other GNOME applications (and also Discord itself!). To implement this, follow these steps:

 Create a new section in the Preferences menu for theme settings.
 Add a dropdown menu to allow users to choose between the light and dark, and adaptive themes. (adaptive changes based on system theme)
 Connect the dropdown menu to the corresponding function that applies the selected theme to the application.
 Save the user's theme preference, so it persists across application restarts.

Thank you for considering this!

**Comment by diamondburned** [comment]
gtkcord4 does have a light theme as well. However, it only works if your Discord's user settings are also set to light theme.

Adding a toggle switch for this should be trivial enough, though.

**Comment by TheKrafter** [comment]
offtopic: this proposal sounds very long-winded and Ai-generated lol

**Comment by markski1** [comment]
It might also be dependant on your system theme? gtkcord runs in light theme on my laptop by default even though my user settings for the native client are dark mode (this is convenient for me anyways since I prefer my laptop be in light mode which is where I use gtkcord, but I imagine this might annoy some)

**Comment by searinminecraft** [comment]
![image](https://github.com/diamondburned/gtkcord4/assets/114207889/c927907e-213b-480f-8562-b8b9f9e27d82)

you can see here, i have light theme. this is just because my theme is set to a light theme.

**Comment by LSeelig** [comment]
> I don't think I check that option; I have no clue what it is called in the `user_options` block. You can set this, though:
> 
> ![image](https://private-user-images.githubusercontent.com/8463786/306907074-16182d9e-7983-421b-b96e-6c307a1f3732.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2Mzc5ODAsIm5iZiI6MTcwODYzNzY4MCwicGF0aCI6Ii84NDYzNzg2LzMwNjkwNzA3NC0xNjE4MmQ5ZS03OTgzLTQyMWItYjk2ZS02YzMwN2ExZjM3MzIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjJUMjEzNDQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmIxMTYwYjZlODJkMjk5MGRhYzMzYTZlODI4MTA0NWUyOGRlYjE4MWMzYWNhOWE3YjEyMWIzMzA0ZGVlMjgyYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.4EB4-Rt47wHHOwmJiWb0akv_jtX4clu7LpIAS4FRptY)

Ah. Sorry; don't know how I missed it.

**Comment by diamondburned** [comment]
Closing this issue since it seems to be fixed.
