### ISSUE TITLE
undefined symbol: g_task_set_static_name

### ISSUE THREAD

**Issue by ravener** [diamondburned/gtkcord4#133]
I'm on Ubuntu MATE 22.04 LTS and running gtkcord gives me:
```
$ ./gtkcord4
./gtkcord4: symbol lookup error: ./gtkcord4: undefined symbol: g_task_set_static_name
```
Latest release suffered from issue #116 so I downloaded the latest nightly build and I get this now.

**Comment by diamondburned** [comment]
Uh oh, seems like this is because of the version bump. This is only available since Gio 2.76, but I'm not sure why gtkcord4 is needing it. gotk4 itself is generated against Gio 2.68, so it shouldn't directly be pulling this.

You might have to build the binary yourself.

**Comment by nbuechner** [comment]
Building it myself on Ubuntu 22.04 seems also impossible because of the needed library versions.
I get the same error on the binary release.

**Comment by diamondburned** [comment]
> Building it myself on Ubuntu 22.04 seems also impossible because of the needed library versions.

The needed library versions for building is still the same. It's the libraries that the binary was built against that matters. Building it yourself against the older libraries should still work normally.

**Comment by Blackilykat** [comment]
Building it using `go install -v github.com/diamondburned/gtkcord4@latest` and then running it gives me this error.
Using Debian 12

**Comment by Joao620** [comment]
> Building it using `go install -v github.com/diamondburned/gtkcord4@latest` and then running it gives me this error. Using Debian 12

I was having this issue, but after building myself worked fine. Can you run `apt list -a libadwaita-1-0`?

**Comment by diamondburned** [comment]
Closing this since it seems to be a user environment issue. If this still doesn't work, try using the Flatpak.
