### ISSUE TITLE
Missing i18n

### ISSUE THREAD

**Issue by Penfore** [diamondburned/gtkcord4#134]
I would like to contribute with translation, but I'm not familiar with generating the initial files.

**Comment by diamondburned** [comment]
Unfortunately, gtkcord4 doesn't have any localization/internationalization :(

I never intended for gtkcord4 to grow this large...

**Comment by VxlerieUwU** [comment]
I could help with french and a bit of german translations too

**Comment by diamondburned** [comment]
Replaced with https://github.com/diamondburned/gtkcord4/issues/138 which will track the progress of i18n.
