### ISSUE TITLE
How do I change the font size?

### ISSUE THREAD

**Issue by avdb13** [diamondburned/gtkcord4#135]
All my other programs still depend on `gtk3` which let's you change this easily with a program like `lxappearance`. I think it would be handy if the default keybindings (ctrl++/ctrl+-) allowed for this behavior unless there's a way to change the font size for all `gtk4` programs like with `gtk3`.

**Comment by diamondburned** [comment]
You can probably do

```css
* {
  font-size: 1.2em;
}
```
?
