### ISSUE TITLE
How can I install this app on Windows 11?

### ISSUE THREAD

**Issue by MuerteRoja** [diamondburned/gtkcord4#137]
I want install gtkcord4 on my Windows 11 but I dont know how to do that

**Comment by diamondburned** [comment]
See https://github.com/diamondburned/gtkcord4/issues/42.

**Comment by MuerteRoja** [comment]
In short, “I don't use the Windows operating system, therefore I cannot or do not know how to adapt the application for this operating system in question.” Did you know that there is something called virtual machines? I'm telling you as a curious fact, you can use an operating system within another operating system, perhaps, perhaps, that can help you in the future to be able to adapt the application.

**Comment by jernejs** [comment]
Program's author does not use Windows, and does not owe you to set up a Windows VM just because that's what you use.

**Comment by MuerteRoja** [comment]
Hello, good afternoon, sorry, not only and only me, but 85% of the people in humanity who also use this operating system and want to belong to the group of those people whose data and privacy are theirs and not that of any monopoly or company , this is where you need to be intelligent and know how to interpret these things, a pleasure to meet you by a certain anonymous gentleman.

**Comment by diamondburned** [comment]
I'm sorry, but 85% of humanity doesn't have to do with a small piece of program that I wrote in my free time.
