### ISSUE TITLE
[bug] Build doesn't work anymore

### ISSUE THREAD

**Issue by 32bitx64bit** [diamondburned/gtkcord4#153]
If you try copy and pasting the build instructions from the repo you get a error, doing it via git clone then go install works fine.

**Comment by diamondburned** [comment]
What is the error?

**Comment by 32bitx64bit** [comment]
> What is the error?

" The go.mod file for the module providing named packages contains one or
        more replace directives. It must not contain directives that would cause
        it to be interpreted differently than if it were the main module.
"

**Comment by diamondburned** [comment]
This should work now. However, there's no guarantee that I won't rely on `replace` in the future as well.
