### ISSUE TITLE
aarch64 dependecies only in x86_64

### ISSUE THREAD

**Issue by Dividfoxx** [diamondburned/gtkcord4#157]
can get Golang but **GTK4** and **gobject-introspection** seem to be exclusive to **x86_64** architecture, Anyone know a workaround to get gtkcord4 to run?

**Comment by diamondburned** [comment]
These are definitely not exclusive to x86_64 architecture. I'm able to run them on my Macbook M1.

This sounds like a distro issue. Perhaps try the Flatpak?

**Comment by diamondburned** [comment]
Unsure if this issue is still relevant, but it doesn't seem to be a gtkcord4 issue. Closing, but feel free to keep commenting on this.
