### ISSUE TITLE
Installing Gives Go Error

### ISSUE THREAD

**Issue by n128-98** [diamondburned/gtkcord4#171]
trying to install from the Go script gives the error  
        The go.mod file for the module providing named packages contains one or
        more replace directives. It must not contain directives that would cause
        it to be interpreted differently than if it were the main module.

**Comment by n128-98** [comment]
Using Debian

**Comment by n128-98** [comment]
decided to use git and use go install in the directory

**Comment by diamondburned** [comment]
Fixed by releasing v0.0.13. `go install ...@latest` should now grab that version.

**Comment by n128-98** [comment]
still gives the same error, tried to install through source, but was missing several dependencies so it exited compilation

**Comment by diamondburned** [comment]
Do `...@v0.0.13`. Go needs a bit to be notified that a new release has been created.
