### ISSUE TITLE
On high-DPS screens, images are unpleasantly small

### ISSUE THREAD

**Issue by aaannestad** [diamondburned/gtkcord4#180]
I'm running gtkcord4 on a 4k screen, and the images displayed in the feed for a given channel are very unpleasantly small. Not _completely_ uselessly small, but enough so that I pretty much have to click on every single one to get much out of them.

This would be not _too_ much of an issue if there was an in-app full-size image popup, but as it is opening each image kicks me back to the browser every time, which is a very inconvenient interaction flow. Dynamic image preview resizing based on the message width setting would also solve the issue. As it is, though, reading through image-focused channels on a 4k monitor without _some_ convenient means to make them larger is miserable enough to be a barrier to me using gtkcord4 as my regular Discord client.

You can see how small they are relative to the text here - 
![image](https://github.com/diamondburned/gtkcord4/assets/91560337/f6c858ae-2e16-4f64-945b-18ef3ab51072)

Compare that to the official Discord client - 
![image](https://github.com/diamondburned/gtkcord4/assets/91560337/cca6915b-bf10-4ec3-9ff4-1683cce32a3c)

**Comment by diamondburned** [comment]
What's the scaling factor of your 4K display?

**Comment by aaannestad** [comment]
125%.

**Comment by diamondburned** [comment]
Is this an issue with 175% scale factor? That's what I seem to use.

**Comment by diamondburned** [comment]
You can also confirm that this is in fact a scaling issue and not just gtkcord4's image size being too small by running with `WAYLAND_DISPLAY= gtkcord4`.

**Comment by aaannestad** [comment]
I guess it's a scaling issue (`WAYLAND_DISPLAY= gtkcord4` still has tiny images), but for every other purpose 125% is fine and I _strongly_ prefer it to 175%. I would rather have a way to scale just image previews in gtkcord4 rather than scale _everything else on screen_ just to make that one issue better!

**Comment by diamondburned** [comment]
> `WAYLAND_DISPLAY= gtkcord4` still has tiny images

Then it's not a scaling issue. It just seems like a gtkcord4's image size being too small issue.

**Comment by diamondburned** [comment]
Commit https://github.com/diamondburned/gtkcord4/commit/9c86416db26b8875a3ffcaaa4f73e5e375f5330e adds new preferences to increase the dimension limits. Try increasing it on your end.

**Comment by aaannestad** [comment]
That is _vastly_ better. Still a shame there's no in-app full-image viewer, but this makes gtkcord4 at least livable. Thank you!

**Comment by diamondburned** [comment]
This is fixed now, so I'm closing this issue.

I have [an image viewer dialog implemented in chatkit](https://github.com/diamondburned/chatkit/blob/main/components/embed/viewer.go), but the panning and zooming aren't working well at the moment.

Perhaps someone else could give it a look?
