### ISSUE TITLE
0.0.15 release archives don't contain the dbus service file

### ISSUE THREAD

**Issue by txtsd** [diamondburned/gtkcord4#185]
The file is missing in the .tar.zst archives.

**Comment by diamondburned** [comment]
Should be fixed with 2d86201c37ba7d4706ef33296cadb34049ec6a0d then caa4e58effe7fa82a7e921c02a1440dc387a9474, but I'll wait for the artifacts to be built and confirm them before making `0.0.15-1`.

**Comment by diamondburned** [comment]
Released `0.0.15-1` for this.
