### ISSUE TITLE
Confirmation dialog on Delete

### ISSUE THREAD

**Issue by diamondburned** [diamondburned/gtkcord4#188]
I keep hitting this button by accident -_-, it really needs a dialog.

We can have the dialog be a toggleable option in Preferences.

**Comment by Quik2007** [comment]
It would also be great if the dialog was automatically skipped when pressing Shift (which is the way the first-party client does it)

**Comment by diamondburned** [comment]
> It would also be great if the dialog was automatically skipped when pressing Shift (which is the way the first-party client does it)

This turns out to be way harder than it needs to be on GTK. I'm not sure how to do this properly (i.e. with a `PopoverMenu`, which is what we're using right now). Pressing Shift also drops it into the mnemonic mode, which lets you do <kbd>Shift</kbd> + <kbd>D</kbd> to trigger a Delete.

**Comment by diamondburned** [comment]
This should work for now:

<img src="https://github.com/diamondburned/gtkcord4/assets/8463786/58e1c352-c8e3-404c-81e9-302337b8e592" width="400" />

The Delete button is probably red on the proper Adwaita theme. I'm using a custom theme at the moment. A new setting ("Ask Before Deleting") will also be added.

**Comment by diamondburned** [comment]
I'm closing this issue for now. Please open a new issue if you feel like the holding-Shift feature is worth adding.
