### ISSUE TITLE
Show guild title on hover (Discord-style)

### ISSUE THREAD

**Issue by ThatOneCalculator** [diamondburned/gtkcord4#194]
Discord electron client:

https://github.com/diamondburned/gtkcord4/assets/44733677/86fbbe5e-9cf6-4cb6-8de9-8822333cefd2

gtkcord4:

https://github.com/diamondburned/gtkcord4/assets/44733677/0aad1ea5-c393-4461-b5a0-d9db56a48d8c

**Comment by diamondburned** [comment]
There is a hover, it just doesn't show up instantly:

![image](https://github.com/diamondburned/gtkcord4/assets/8463786/80c85e03-3ce0-4282-ae0f-6f7ab4b484aa)

**Comment by ThatOneCalculator** [comment]
Strange...I can't get that to show for me.

**Comment by diamondburned** [comment]
This is implemented as a proper popover as of 7354701:

![image](https://github.com/diamondburned/gtkcord4/assets/8463786/abb41a52-2fa7-439f-8cd5-c0dadeccfb7d)

**Comment by ThatOneCalculator** [comment]
Oooh, looks clean!!
