### ISSUE TITLE
Channel list aesthetics

### ISSUE THREAD

**Issue by ThatOneCalculator** [diamondburned/gtkcord4#196]
Discord electron client with the [DNOME](https://github.com/GeopJr/DNOME) theme:

![image](https://github.com/diamondburned/gtkcord4/assets/44733677/b904aad8-6254-4947-aafe-944dba588327)

gtkcord4:

![image](https://github.com/diamondburned/gtkcord4/assets/44733677/fea992bc-4aaa-4664-8bcc-696034204930)

Currently (imo), the gtkcord4 version feels far less inviting, mainly due to a lack of padding, small text, and drop-down style.

**Comment by diamondburned** [comment]
Fixing this would likely begin at moving the channel list to use `ColumnView` instead of `TreeView`, which I've tried before, but it's just a pain in the ass since gotk4 can't do subclassing yet... (blame GTK for its awful lack of documentation!)

An alternative would be to just use regular Popover + List widgets like gtkcord3 had, but manually handling state changes with that was really painful compared to using a `TreeStore`.

**Comment by ThatOneCalculator** [comment]
Ah.

> blame GTK for its awful lack of documentation!

I'm not a GTK developer, but have you tried [Bibliotheca](https://flathub.org/apps/app.drey.Biblioteca)?

**Comment by diamondburned** [comment]
It's more about the lack of documentation (in particular, subclassing documentation), but that's a neat app.

**Comment by diamondburned** [comment]
Implemented in https://github.com/diamondburned/gtkcord4/commit/2f8a342074f420ef5a21dfb74e8c389d5d77d8ba.

**Comment by ThatOneCalculator** [comment]
Nice! How do I install the nightly with this? I'm currently using `go install -v github.com/diamondburned/gtkcord4@latest`

**Comment by ThatOneCalculator** [comment]
Hm... I did `go install -v github.com/diamondburned/gtkcord4@nightly` which seems to have worked since the about page shows the version as `git (ca66b8d)`, but the channel list still looks the same-ish

![image](https://github.com/diamondburned/gtkcord4/assets/44733677/9cab0bac-c2f9-41a3-9041-54676f5368b6)

**Comment by diamondburned** [comment]
ca66b8d is not recent enough. Try doing `@43d581a`.

**Comment by ThatOneCalculator** [comment]
Awesome, works great!
