### ISSUE TITLE
Update to GNOME 45 aesthetics

### ISSUE THREAD

**Issue by diamondburned** [diamondburned/gtkcord4#197]
![image](https://github.com/diamondburned/gtkcord4/assets/8463786/8db54e0f-9b49-46cf-a7db-d208dcf1b5db)

Differences:

- Distinct split pane
- No joined headerbar
- Darker left-panel, brighter main content

**Comment by AbrarSL** [comment]
https://gnome.pages.gitlab.gnome.org/libadwaita/doc/main/migrating-to-breakpoints.html

This could probably help.

**Comment by diamondburned** [comment]
Can I expect most outdated distros (e.g. Ubuntu, Debian, etc.) to have libadwaita 1.4 by now?

**Comment by AbrarSL** [comment]
Ubuntu 23.10 which is the latest release of Ubuntu has 1.4 the 22.04 LTS does not. As for Debian. The current stable release of Debian (which is 12) has 1.2

**Comment by TriVoxel** [comment]
> Can I expect most outdated distros (e.g. Ubuntu, Debian, etc.) to have libadwaita 1.4 by now?

Since you distribute with Flatpak, it shouldn't matter as the dependency is cross-platform, same with AppImage if you bundle it. Should be good!

**Comment by diamondburned** [comment]
This seems more ideal:

![image](https://github.com/diamondburned/gtkcord4/assets/8463786/9ecf49ab-982b-4c22-bed9-140f0aecec4d)

I'm not sure what to do with the guilds list though.
