### ISSUE TITLE
symbol lookup error

### ISSUE THREAD

**Issue by HalanoSiblee** [diamondburned/gtkcord4#198]
running gtkcord4 gives me symbol lookup error
`./gtkcord4: symbol lookup error: /usr/lib/libgtk-4.so.1: undefined symbol: g_assertion_message_cmpint`
![image](https://github.com/diamondburned/gtkcord4/assets/70325026/ad11b241-b7bd-4acd-8402-948e9e5acce8)

**Comment by diamondburned** [comment]
Make sure your GTK4 is new enough. If you're unsure, use the Flatpak: https://flathub.org/apps/so.libdb.gtkcord4

Closing this issue since it's distro-specific.
