### ISSUE TITLE
AppImage opens... git file?

### ISSUE THREAD

**Issue by setPrimse** [diamondburned/gtkcord4#20]
I hope it's self explanatory.
Whenever i open the client, the client opens file called "https://github.com/diamondburned/gtkcord4".

I use manjaro-gnome, maybe that's the problem (i hope not).

**Comment by setPrimse** [comment]
Okay, now i know that sudo actually start the "gtkcord4".

**Comment by diamondburned** [comment]
What AppImage are you talking about? I don't distribute any AppImages.

**Comment by setPrimse** [comment]
The .desktop file, sorry.

**Comment by diamondburned** [comment]
I'm not sure how you installed the binary. This seems more like general Linux help, so you might have better luck asking in other places instead. I don't provide any official ways of installing gtkcord4 on any platforms other than moving the binary into `$PATH`.
