### ISSUE TITLE
Feature: plus Emoji reaction

### ISSUE THREAD

**Issue by hybras** [diamondburned/gtkcord4#207]
Discord allows you to react to the last message in a channel by sending a message of the form "+:emoji_name:". Implementing this would avoid adding any new ui elements.

**Comment by diamondburned** [comment]
Why is this issue closed? This feature has not been implemented yet and I'd like to implement this!

**Comment by hybras** [comment]
Oh there was no response so I assumed it wouldn't be picked up. Didn't want it clogging up the issue list

**Comment by diamondburned** [comment]
You're good.
