### ISSUE TITLE
[Bug] every thread in channel shows instead of active ones

### ISSUE THREAD

**Issue by ThatOneCalculator** [diamondburned/gtkcord4#211]
Discord:

![image](https://github.com/diamondburned/gtkcord4/assets/44733677/2de30264-2429-4783-9fae-d76bbd191c7d)

gtkcord4:

![image](https://github.com/diamondburned/gtkcord4/assets/44733677/0c06190c-78fb-48f8-8cba-f139d79f9b73)

**Comment by diamondburned** [comment]
This is less of a bug and more of an intended functionality, since there is no thread browser, so this is the only way to join a thread currently.

Related issue: https://github.com/diamondburned/gtkcord4/issues/142
