### ISSUE TITLE
Server icons and avatars requesting too large of a size

### ISSUE THREAD

**Issue by Techwizz-somboo** [diamondburned/gtkcord4#216]
I'm using the flatpak on postmarketOS, and am having a problem with no icons or profile pictures showing. The pictures are being requested above the maximum image size of 100. It's requesting 192.

For example

```
2024/01/05 05:28:02 imgutil: unexpected status code 400 getting "https://cdn.discordapp.com/avatars/479749233155768331/06d2c4ee8a0fd4570c184c088c8edaa8.png?size=192"
```

This will lead you to an error

```
https://cdn.discordapp.com/avatars/479749233155768331/06d2c4ee8a0fd4570c184c088c8edaa8.png?size=192
```

If you change the size to 100 or lower it works

```
https://cdn.discordapp.com/avatars/479749233155768331/06d2c4ee8a0fd4570c184c088c8edaa8.png?size=100
```

**Comment by diamondburned** [comment]
Nightly should have this fix now. Please try that build once it's gone through.

**Comment by Techwizz-somboo** [comment]
> Nightly should have this fix now. Please try that build once it's gone through.

Thanks for the prompt fix, I'll try it out tomorrow!

**Comment by Techwizz-somboo** [comment]
I forgot to follow up. It's fixed, thanks!
