### ISSUE TITLE
feature request: add a way to send multi-line messages on a mobile keyboard

### ISSUE THREAD

**Issue by floppydiskette** [diamondburned/gtkcord4#26]
currently as far as i can tell, there isn't a way to create a newline with the default on-screen keyboard present in phosh (this may not be the case in other mobile UIs).
i recognize that — without access to a way to create custom keyboards — this may be a difficult feature to implement; however, it would probably be not too hard to hack something together (like using a combination of ctrl+return to create a newline, as — at least phosh — provides a terminal keyboard with an available ctrl character). this of course may not be desired though, so feel free to take this request as you please

**Comment by diamondburned** [comment]
I'll work on adding the Preferences button in first, then adding this should be simple.

**Comment by diamondburned** [comment]
This commit adds a preference toggle, but it would be nice if GTK has a way to know if an OSK is being used.
