### ISSUE TITLE
`aarch64-linux-gnu-pkg-config: exec: "aarch64-linux-gnu-pkg-config": executable file not found in $PATH`

### ISSUE THREAD

**Issue by DUOLabs333** [diamondburned/gtkcord4#3]
I'm trying to build it, but it keeps failing with the error above. On Void (and I'm assuming most Linux distros), it's called `pkg-config`.

**Comment by diamondburned** [comment]
Try inspecting your `go env`. This seems like a build tool misconfiguration, and I probably won't be able to help with that.

**Comment by DUOLabs333** [comment]
I just gave up trying to compile it --- even with your patch, it was taking  over 2 hours (it was compiling your gtk4 bindings).
