### ISSUE TITLE
Ctrl-K for quick navigation

### ISSUE THREAD

**Issue by Vrganj** [diamondburned/gtkcord4#34]
Would be a neat keybind to have.

**Comment by diamondburned** [comment]
The quick switcher is added under the menu.

Shortcuts are not implemented yet. Subclassing support has to be added into gotk4 for that to be feasible in GTK4, and I'm not even close to figuring out a way to do that.

We'll have to deal with that for a while.

**Comment by diamondburned** [comment]
I take that back. I've just figured out a way to do it.

**Comment by diamondburned** [comment]
Implemented in 19cbbb7.

**Comment by diamondburned** [comment]
![image](https://user-images.githubusercontent.com/8463786/174956052-f22bc8ce-db62-408d-a805-55d79b7391bc.png)
