### ISSUE TITLE
Please include instructions for how to run & how to get dependencies (and better build instructions)

### ISSUE THREAD

**Issue by Hedwig7s** [diamondburned/gtkcord4#38]
I am stuck unable to get the precompiled version to run and can't figure out how to build it

**Comment by jonbarrow** [comment]
> The instructions for compiling it is [here](https://github.com/diamondburned/gtkcord4#compiling). If that doesn't work, open an issue elaborating why.

This does not explain the proper way of getting dependencies however. The README lists the names of the dependencies but now where to actually get them or how to install them. For example it is unclear how exactly get the proper GDK/GTK version installed, as even after days of Googling and following guides the compiled binaries do not run and the compilation method also fails (which I have mentioned in this issue https://github.com/diamondburned/gtkcord4/issues/37)

Some proper build steps with either the commands to install the dependencies or the proper place to acquire them would be helpful to newcomers who are not very tech savvy and just want a lightweight Discord client

**Comment by diamondburned** [comment]
> This does not explain the proper way of getting dependencies however. The README lists the names of the dependencies but now where to actually get them or how to install them. For example it is unclear how exactly get the proper GDK/GTK version installed, as even after days of Googling and following guides the compiled binaries do not run and the compilation method also fails (which I have mentioned in this issue #37)

This is outside the scope of the program itself and would fall under [gotk4](https://github.com/diamondburned/gotk4)'s instructions (or just anything GTK4 in general).

It would also be very impractical to have instructions for every single distribution and package manager out there. The only way of compiling gtkcord4 that I really support is simply running

```sh
nix-shell
go build
```

And I'm sure that's not very helpful for most people.

**Comment by jonbarrow** [comment]
I would personally argue that it is perfectly within the scope of a project to include proper instructions on how to acquire/install it's dependencies. Even at the very least linking to the repo in your last reply would be better than how it is now, as that has very detailed instructions for several systems

> The only way of compiling gtkcord4 that I really support is simply running

This is not made clear in the README either. The README implies that all you would need to do to compile is run the `go install` command. Without actually checking the source code it's not clear that you would need Nix at all

**Comment by Hedwig7s** [comment]
Could release built binaries too

**Comment by diamondburned** [comment]
> Without actually checking the source code it's not clear that you would need Nix at all

You don't need Nix. It's just the way that I do it for development.
