### ISSUE TITLE
Server icons and profile pictures not loading

### ISSUE THREAD

**Issue by TriVoxel** [diamondburned/gtkcord4#39]
Using latest release from 10 days ago. All my servers appear as the fallback initials instead of loading the server icons. Inside the servers, nobody's profile pictures appear either. Only default discord pfp users shows up. I get an error like this when I open a folder of servers:
```
2022/07/09 20:26:24 imgutil: Failed to open file “/home/person/.cache/gtkcord4/img2/7bvOBReA8XHMj6akgEbbsYRl=”: No such file or directory
2022/07/09 20:26:24 imgutil: Failed to open file “/home/person/.cache/gtkcord4/img2/0S6Z9qfAx_9coqk7xGjjev6A=”: No such file or directory
2022/07/09 20:26:24 imgutil: Failed to open file “/home/person/.cache/gtkcord4/img2/S6y8vqFIe_yC2Hl0vcp1oxYkt=”: No such file or directory
2022/07/09 20:26:24 imgutil: Failed to open file “/home/person/.cache/gtkcord4/img2/ByKjTXlvHT6mjNH_O4W65NOE=”: No such file or directory
2022/07/09 20:26:24 imgutil: Failed to open file “/home/person/.cache/gtkcord4/img2/PIGFuVe2B1iEWuVruCnqSroI=”: No such file or directory
...
```
This could have something to do with all my servers being organized in folders.
![Screenshot from 2022-07-09 20-29-10](https://user-images.githubusercontent.com/25536957/178128917-a064fa82-215e-4490-9d8e-c1ab1810f4fe.png)
![Screenshot from 2022-07-09 20-30-35](https://user-images.githubusercontent.com/25536957/178128933-1439ce44-f3fe-4bd2-a330-fb3c68001e20.png)
PFP issue:
![Screenshot from 2022-07-09 21-02-09](https://user-images.githubusercontent.com/25536957/178129561-a42f4f53-cb2a-4343-b250-502e92ae2536.png)

**Comment by diamondburned** [comment]
I'm trying to fix this, but you'll have to either use the CI to compile or build the code yourself for now.

**Comment by diamondburned** [comment]
Latest commit should have a fix that gives better errors, which should yield the actual reason why the images aren't loading.

**Comment by TriVoxel** [comment]
I actually can't compile. Fedora 36. I'll make a separate issue.

**Comment by Alasofia** [comment]
I'm having the same issue with images but with two different (repetitive) errors.
imgutil: unexpected status code 400 getting "link to a file on discord's cdn"
imgutil: URL not found (cached)

This is on a OnePlus 6T with pmOS edge on Phosh.
The exact same bug exists on the latest commit (built locally) and the latest release.

**Comment by Alasofia** [comment]
Installed Mobian to test that too, and the same issue persists.

**Comment by TriVoxel** [comment]
No longer an issue.

**Comment by Techwizz-somboo** [comment]
I'm using the flatpak on postmarketOS, and am having a problem with no icons or profile pictures showing. The pictures are being requested above the maximum image size of 100. It's requesting 192.

For example

```
2024/01/05 05:28:02 imgutil: unexpected status code 400 getting "https://cdn.discordapp.com/avatars/479749233155768331/06d2c4ee8a0fd4570c184c088c8edaa8.png?size=192"
```

This will lead you to an error

```
https://cdn.discordapp.com/avatars/479749233155768331/06d2c4ee8a0fd4570c184c088c8edaa8.png?size=192
```

If you change the size to 100 or lower it works

```
https://cdn.discordapp.com/avatars/479749233155768331/06d2c4ee8a0fd4570c184c088c8edaa8.png?size=100
```

**Comment by diamondburned** [comment]
Interesting. There should be a function that rounds the size to a power of 2, but I guess that function is not working right?

**Comment by diamondburned** [comment]
You should make a separate issue for this.

**Comment by Techwizz-somboo** [comment]
> You should make a separate issue for this.

Done, #216.

Thanks for the response btw!

**Comment by diamondburned** [comment]
f613323 contains a fix to the previous commit because I had the argument flipped :p

It should actually be fixed now.
