### ISSUE TITLE
Cannot Compile on Fedora 36

### ISSUE THREAD

**Issue by TriVoxel** [diamondburned/gtkcord4#41]
GTKCoord4 doesn't compile with the instructions provided in README. It claimed to have grabbed all these when I ran it the first time.

```
$ go version
...
go version go1.18.3 linux/amd64

$ go install -v github.com/diamondburned/gtkcord4@latest
...
github.com/diamondburned/gotk4/pkg/core/gerror
github.com/diamondburned/gotk4/pkg/cairo
github.com/diamondburned/gotk4/pkg/graphene
# pkg-config --cflags  -- glib-2.0 gobject-introspection-1.0
Package gobject-introspection-1.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gobject-introspection-1.0.pc'
to the PKG_CONFIG_PATH environment variable
Package 'gobject-introspection-1.0', required by 'virtual:world', not found
pkg-config: exit status 1
# pkg-config --cflags  -- graphene-gobject-1.0 graphene-1.0
Package graphene-gobject-1.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `graphene-gobject-1.0.pc'
to the PKG_CONFIG_PATH environment variable
Package 'graphene-gobject-1.0', required by 'virtual:world', not found
Package 'graphene-1.0', required by 'virtual:world', not found
pkg-config: exit status 1
# pkg-config --cflags  -- cairo cairo-gobject gobject-2.0
Package cairo was not found in the pkg-config search path.
Perhaps you should add the directory containing `cairo.pc'
to the PKG_CONFIG_PATH environment variable
Package 'cairo', required by 'virtual:world', not found
Package 'cairo-gobject', required by 'virtual:world', not found
pkg-config: exit status 1
```

_Originally posted by @TriVoxel in https://github.com/diamondburned/gtkcord4/issues/39#issuecomment-1181674161_

**Comment by diamondburned** [comment]
Seems like your build environment isn't configured properly. Try following through with whatever is on [gotk4-examples](https://github.com/diamondburned/gotk4-examples)'s README.

If that doesn't work, try using Nix with `nix-shell`, then run `go` in there.

**Comment by Commenter25** [comment]
Running `sudo dnf install gtk4-devel gobject-introspection-devel` fixes the issue. Install `libadwaita-devel` as well to build against libadwaita.

**Comment by TriVoxel** [comment]
> Running `sudo dnf install gtk4-devel gobject-introspection-devel` fixes the issue. Install `libadwaita-devel` as well to build against libadwaita.

@diamondburned indeed, this fixes the issue. I can now compile successfully with and without libadwaita. Awesome!

**Comment by hybras** [comment]
@TriVoxel mind closing this?

**Comment by diamondburned** [comment]
This issue seems fixed. I'm closing this.
