### ISSUE TITLE
Windows version

### ISSUE THREAD

**Issue by GornikSamil** [diamondburned/gtkcord4#42]
Is it possible to make a windows version? I do not use Linux anymore, and I really like Gtkcord becouse it is very good.
It would be great if there was a windows version. I hope you will respond on my message. Thank you.

**Comment by diamondburned** [comment]
gtkcord4 should compile on Windows fine. I won't try and provide cross-compiling for Windows, especially because Nixpkgs' mingw environment is super broken. You'll have to do that yourself.

**Comment by Cynosphere** [comment]
It won't compile because `cgosymbolizer` requires Unix headers that are only available in MSYS2, when all the packages that are required are only in MinGW64.

**Comment by diamondburned** [comment]
> It won't compile because `cgosymbolizer` requires Unix headers that are only available in MSYS2, when all the packages that are required are only in MinGW64.

`cgosymbolizer` is now Linux-only: https://github.com/diamondburned/gtkcord4/blob/main/cgosymbolizer_linux.go

**Comment by Cynosphere** [comment]
Tried with `@main` instead of `@latest` and got as far as `gotk4/pkg/gtk/v4` before running into diamondburned/gotk4#56.

This was supposedly fixed yet I'm still having the issue on Go 1.19.2...

**Comment by PrincessAkira** [comment]
Any1 figured it out yet?

**Comment by diamondburned** [comment]
> This was supposedly fixed yet I'm still having the issue on Go 1.19.2...

The [fix](https://github.com/golang/go/commit/5bc8fa74f5186dc7898126487c31283d0766a5b4) was tagged for [go1.20rc1](https://github.com/golang/go/releases/tag/go1.20rc1). You might want to try again with Go 1.20.x.

**Comment by PrincessAkira** [comment]
> > This was supposedly fixed yet I'm still having the issue on Go 1.19.2...
> 
> The [fix](https://github.com/golang/go/commit/5bc8fa74f5186dc7898126487c31283d0766a5b4) was tagged for [go1.20rc1](https://github.com/golang/go/releases/tag/go1.20rc1). You might want to try again with Go 1.20.x.

It does run through but theres no file created in GoPath

**Comment by diamondburned** [comment]
> It does run through but theres no file created in GoPath

I'm not sure what you mean by this but the error looks like `CGO_ENABLED` is off? Are you building this in the right environment?

**Comment by diamondburned** [comment]
There is now a Windows version. See https://github.com/diamondburned/gtkcord4/issues/118.

**Comment by diamondburned** [comment]
Whoops! It's actually fixed now!
