### ISSUE TITLE
Homebrew Package

### ISSUE THREAD

**Issue by hybras** [diamondburned/gtkcord4#45]
I've created a [homebrew package for gtkcord4](https://github.com/hybras/homebrew-tap/blob/main/Formula/gtkcord4.rb). Homebrew is a package manager for macos, and at this point the defacto one. Currently I have a github action that checks for new version's once a week. I'm interested in donating the package to you so that you can update it in CI / whenever new versions are released / on demand. 

Updating this package means updating the url and hash (the version is inferred from the url). I can help in automating updates if u have an existing ci workflow (it seems u dont). My goal is to get updates quicker by integrating this into ur workflow.

**Comment by diamondburned** [comment]
I do have a CI workflow at https://github.com/diamondburned/gtkcord4/blob/main/.build.yml using build.sr.ht. However, most of what it's doing is just building Linux amd64 and arm64 binaries on release as well as basic linting.

I'm not sure if I'm willing to take the role of maintaining any packages. It seems to be a lot of work on top of what I already have, and it's always been up to others to package this.

**Comment by diamondburned** [comment]
Also side note: I've looked through your package, and it seems to be adding `libcanberra` as a build dependency. In reality, this is a runtime dependency where the process will execute a binary that `libcanberra` provides, and I'm not sure if this is the case for macOS. The dependency is also optional; gtkcord4 will use a default chime if the binary is missing.

**Comment by hybras** [comment]
> ... `libcanberra` as a build dependency. In reality, this is a runtime dependency ...
👍
