### ISSUE TITLE
Dark mode theme not gen

### ISSUE THREAD

**Issue by Skyyzzz** [diamondburned/gtkcord4#48]
(sorry my gramatical errors i aren't american native so...)

I make an manual installation with git clone - I tried make with the README file, but i can't execute the files and find the folders. 
The gtkcord still open normally, but the "user.css" its not generate too. I tried to copy a config.css of gtkcord3 and some similar files.
Aparently its all right with performance, just the colors is fixed in lightmode, and its little disturbing. 
anyone knows how to fix that or make a custom theme for this?

**Comment by diamondburned** [comment]
See https://github.com/diamondburned/gtkcord4/issues/24. Latest commit should already switch to a dark theme if your account uses a dark theme.

**Comment by godspeedfw** [comment]
> See #24. Latest commit should already switch to a dark theme if your account uses a dark theme.

My account uses dark theme but it still doesn't switch.

**Comment by diamondburned** [comment]
Try adding a log statement before [this line](https://github.com/diamondburned/gtkcord4/blob/main/internal/gtkcord/window/window.go#L145). It should give you `dark`.

**Comment by diamondburned** [comment]
It turns out the event handler for the ready event was never reached because I forgot to add the event into the filter...

That was rather stupid of me.
