### ISSUE TITLE
Does not show all Servers that I am part of

### ISSUE THREAD

**Issue by ghost** [diamondburned/gtkcord4#5]
I just compiled this and logged in using my token and here is what I see on the left panel:
![Screenshot from 2022-04-16 21-01-14](https://user-images.githubusercontent.com/78986003/163688079-0d8ddcee-a04b-4ca2-9d54-ddeb6755e7e5.png)

while this is what I see on the WebClient:
![discord-normal](https://user-images.githubusercontent.com/78986003/163688085-6cf15dcd-b048-4c84-b8f0-500727156dee.png)

So there are two Servers missing (sadly, the first of the bunch is the most crucial one for me :/)

**Comment by metalune1** [comment]
If there is any info you need for debugging regarding what servers these are and potentially what kinds of channels they have (maybe it is related to that?) or what server-side settings they have, feel free to ask and I'll try to find out

**Comment by diamondburned** [comment]
You can check the code path that's being executed in [guilds.go](https://github.com/diamondburned/gtkcord4/blob/main/internal/gtkcord/sidebar/guilds/guilds.go#L126).

First, check if it's seeing any guild folders. If it is, then maybe the guilds are missing from those folders, so I would need to add code to check missing ones. If it isn't, then perhaps `state.Guilds()` isn't returning all the guilds, which is rather weird. It could just be lazily initialized, but that should still work.

**Comment by metalune1** [comment]
I don't know where in the code I have to look to be honest, it would be nice knowing which functions load what, I'm sure there is one which just iterates through all of the loaded guilds, right? (I'm not all that well-versed in go tbh)

**Comment by diamondburned** [comment]
Commit a8d6292c632888f3de2299c17b615b3c7293d38f should fix this.

**Comment by hybras** [comment]
Should this be closed as stale? I don't see any others with this issue. I cannot reproduce despite being in a dozen servers myself.
