### ISSUE TITLE
libsecret 

### ISSUE THREAD

**Issue by CrafterSvK** [diamondburned/gtkcord4#51]
Would be nice if gtkcord4 implemented libsecret for storing auth data.

**Comment by diamondburned** [comment]
gtkcord4 already uses the system's keyring for storing auth data without using libsecret. If anything is missing, please open a new issue requesting that specific feature.

**Comment by CrafterSvK** [comment]
Yeah I've seen it, it also does not work on 3 machines I tried it on.

**Comment by diamondburned** [comment]
Again, if anything is missing, open a new issue specifically requesting it. Saying "it does not work" won't get you very far; it works just fine for me.
