### ISSUE TITLE
provide a musl-linked binary aswell as the glibc one

### ISSUE THREAD

**Issue by 13-05** [diamondburned/gtkcord4#52]
you have a ci that produces linux binaries, but they're linked against glibc it seems. can you make musl-linked ones aswell? im on void linux (musl) and glibc-linked binaries don't run.

**Comment by TheKrafter** [comment]
according to the [Alpine Wiki](https://wiki.alpinelinux.org/wiki/Running_glibc_programs#gcompat), installing the [gcompat](https://git.adelielinux.org/adelie/gcompat) compatibility layer is all you need to run glibc binaries on musl.

**Comment by 13-05** [comment]
i tried gcompat and it didnt work for this, doesnt apply to me anymore though because i hopped to artix. ill close this issue!

**Comment by diamondburned** [comment]
While I won't be providing musl-linked binaries anytime soon (because CI build times are already ridiculous--I might as well try to run my own GitLab Runner), I do want to try out [nix-appimage](https://github.com/ralismark/nix-appimage), which should be libc-independent.

**Comment by 13-05** [comment]
ooh okay
