### ISSUE TITLE
[Question] How to install GTK4 ?

### ISSUE THREAD

**Issue by KaKi87** [diamondburned/gtkcord4#53]
Hello,

The README says :
> gtkcord4 needs GTK4

It would be nice to also explain how to install it, starting with `apt` package names.

Thanks

**Comment by ZeroQLi** [comment]
A little bit of googling helps a lot

https://github.com/ToshioCP/Gtk4-tutorial/blob/main/gfm/sec2.md

For your help though here are the packages you need to install
`sudo apt-get install libgtk-4-bin libgtk-4-common libgtk-4-dev libgtk-4-doc`

**Comment by KaKi87** [comment]
I also found that somewhere, but thought I was mistaken somehow, because :
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libgtk-4-bin
E: Unable to locate package libgtk-4-common
E: Unable to locate package libgtk-4-dev
E: Unable to locate package libgtk-4-doc
```

**Comment by diamondburned** [comment]
You need Ubuntu 21.04 or later.

The instructions to set up GTK4 are at [gotk4-examples](https://github.com/diamondburned/gotk4-examples#linux---ubuntu). Instructions for setting up GTK4 is out of scope for this repository's README. See https://github.com/diamondburned/gtkcord4/issues/38.

**Comment by KaKi87** [comment]
> You need Ubuntu 21.04 or later.

Oh, that's an unexpected and restrictive requirement.
Would you please add this information to your README ?

> Instructions for setting up GTK4 is out of scope for this repository's README. See #38.

Actually, I totally relate to what OP said there :
> The README lists the names of the dependencies but now where to actually get them or how to install them.

> I would personally argue that it is perfectly within the scope of a project to include proper instructions on how to acquire/install it's dependencies.

Thanks
