### ISSUE TITLE
go4.org/unsafe/assume-no-moving-gc hasn't been updated to assert that it's safe against the go1.19 runtime

### ISSUE THREAD

**Issue by mrredcon** [diamondburned/gtkcord4#55]
Attempting to install gtkcord4-git-r95.8ff24dc-1 from the AUR met me with this error upon launching: 

panic: Something in this program imports go4.org/unsafe/assume-no-moving-gc to declare that it assumes a non-moving garbage collector, but your version of go4.org/unsafe/assume-no-moving-gc hasn't been updated to assert that it's safe against the go1.19 runtime. If you want to risk it, run with environment variable ASSUME_NO_MOVING_GC_UNSAFE_RISK_IT_WITH=go1.19 set. Notably, if go1.19 adds a moving garbage collector, this program is unsafe to use.

goroutine 1 [running]:
go4.org/unsafe/assume-no-moving-gc.init.0()
        go4.org/unsafe/assume-no-moving-gc@v0.0.0-20211027215541-db492cf91b37/untested.go:25 +0x1f4

**Comment by diamondburned** [comment]
This should be fixed in https://github.com/diamondburned/gtkcord4/commit/382fd357c3f11ab382681922c1c7fea1cd751952.
