### ISSUE TITLE
v0.0.4 Macos compile Failure

### ISSUE THREAD

**Issue by hybras** [diamondburned/gtkcord4#66]
I realize macos isn't supported, so feel free to close this.

You're using https://github.com/ianlancetaylor/cgosymbolizer as your symbolizer, which doesn't support macos. Curiously, v0.0.3 still compiled. 

https://github.com/benesch/cgosymbolizer is a drop-in replacement that also supports macos and linux. On linux it delegates to github.com/ianlancetaylor/cgosymbolizer.

I've applied a patch doing this to my macos package

**Comment by diamondburned** [comment]
The best idea seems to just be moving the import to an `x_linux.go` file.
