### ISSUE TITLE
[Request] Flatpak package

### ISSUE THREAD

**Issue by Amanse** [diamondburned/gtkcord4#7]
A Flatpak package would be nice and ease the installation process.
Thanks for all the great work on gtk+golang!!

**Comment by diamondburned** [comment]
I won't be providing a Flatpak package. I don't use Flatpak package, and while I've looked into packaging it, it seems like a pain overall. The closest thing to a package that I'll be willing to provide are Nix package files and prebuilt binaries. For now, the binary CI isn't there yet.

Others are free to package gtkcord4 for Flatpak, and they're free to use this issue to facilitate that, but I will be closing it.

**Comment by Amanse** [comment]
nix packages and binaries will be great!
my cheap ass laptop couldn't compile it or even the gtk4 examples, waiting for binaries, thanks!
