### ISSUE TITLE
Logo proposal 

### ISSUE THREAD

**Issue by ThatOneCalculator** [diamondburned/gtkcord4#71]
Made with Inkscape and AppIconPreview, referencing https://developer.gnome.org/hig/guidelines/app-icons.html

Attachments are in SVG format

# Icon

![gtkcord4](https://user-images.githubusercontent.com/44733677/193492645-881b46a4-2faf-469e-ae69-9dbb57e93ca4.svg)

# Nightly

![gtkcord4_nightly](https://user-images.githubusercontent.com/44733677/193492642-59043a50-18de-410d-bc6a-59c45209f2f1.svg)

# Preview

![image](https://user-images.githubusercontent.com/44733677/193492674-f3380807-e586-48ee-84cf-7bf34bb441f4.png)

**Comment by diamondburned** [comment]
Is there any particular meaning to this shade of purple?

**Comment by ThatOneCalculator** [comment]
Yes there is! The colors used are from the GNOME color palette, see the guidelines I linked :)

**Comment by diamondburned** [comment]
I'm not sure if I'm a fan of this dark shade of purple, though. Is there a lighter color that we can go with?

**Comment by ThatOneCalculator** [comment]
I tried with different colors and I think this one is the best (especially since it matches other purple icons) but I can make some variations in the morning, it's 2AM here

**Comment by ThatOneCalculator** [comment]
Here's an alt:

![discord_adwaita_alt](https://user-images.githubusercontent.com/44733677/193662855-a347b813-2bbd-4b7d-b3bd-cb810deb94ab.svg)

**Comment by diamondburned** [comment]
I like this shade a bit more. Can you file a PR to replace /[internal](https://github.com/diamondburned/gtkcord4/tree/main/internal)/[icons](https://github.com/diamondburned/gtkcord4/tree/main/internal/icons)/[png](https://github.com/diamondburned/gtkcord4/tree/main/internal/icons/png)/logo.png?

**Comment by diamondburned** [comment]
Actually, since this is probably made as an SVG, can that be added into `/svg` as well?
