### ISSUE TITLE
Proper Application title and icon

### ISSUE THREAD

**Issue by im-viriv** [diamondburned/gtkcord4#75]
Currently when using the client on gnome (using the aur build) you get no proper application title and no symbolic icon to go with it
![image](https://user-images.githubusercontent.com/30769091/195999238-2ea69552-0d1c-4799-a528-c130e9e340d4.png)

**Comment by diamondburned** [comment]
Does the AUR build install the desktop file properly? I don't maintain the AUR build files.

**Comment by im-viriv** [comment]
the .desktop file i could find does not completely match the one found in the repo but should at least use the proper icon which it also does not, i think this might be a case of misplaced assets or something similar

(.desktop file found on my system:)
```
[Desktop Entry]
Name=gtkcord4
Comment=A lightweight Discord client which uses GTK4 for the user interface.
Exec=gtkcord4
Icon=gtkcord
Terminal=false
Type=Application
Categories=Network;InstantMessaging;P2P;
```

**Comment by diamondburned** [comment]
I just took a look at the PKGBUILD. The icon is not installed: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=gtkcord4-git#n47.

**Comment by diamondburned** [comment]
You might want to reach out to @txtsd who's the maintainer of this PKGBUILD.

I'll be closing this issue here since it doesn't have to do with this repository (and there's nothing I can do about this PKGBUILD), but you're free to continue using it for discussions.

**Comment by txtsd** [comment]
I haven't updated the AUR package since r18. I'll get around to it today, Thanks for the heads-up.

**Comment by txtsd** [comment]
@im-viriv AUR package is updated!

**Comment by im-viriv** [comment]
Cool! Thx a lot you guys
