### ISSUE TITLE
Cannot use right-click context menus when on mobile/using touchscreen

### ISSUE THREAD

**Issue by DremOSDeveloperTeam** [diamondburned/gtkcord4#77]
It's currently impossible to use right-click context menus. For example, by long-pressing a message to attempt to reply to it. Instead of staying open, it closes as you lift your finger.

**Comment by diamondburned** [comment]
I'm not even sure how I should handle this in GTK. The responsible function is in `gotkit/gtkutil/gestures.go`:

```go
// BindRightClickAt is a version of BindRightClick with accurate coordinates
// given to the callback.
func BindRightClickAt(w gtk.Widgetter, f func(x, y float64)) {
	c := gtk.NewGestureClick()
	c.SetButton(3)       // secondary
	c.SetExclusive(true) // handle mouse only
	c.ConnectAfter("pressed", func(nPress int, x, y float64) {
		if nPress == 1 {
			f(x, y)
		}
	})

	l := gtk.NewGestureLongPress()
	l.SetTouchOnly(true)
	l.ConnectAfter("pressed", func(x, y float64) {
		f(x, y)
	})

	widget := gtk.BaseWidget(w)
	widget.AddController(c)
	widget.AddController(l)
}
```

At first glance, it seems to work. I'm not sure what else I should add.

**Comment by DremOSDeveloperTeam** [comment]
I just happened to find out that another application, Paper, has the same issue, which means that this is more than likely a GNOME or Phosh issue, or an issue with my system in particular. Closing this issue, thank you for your help!
