### ISSUE TITLE
Multithreaded compilation?

### ISSUE THREAD

**Issue by CCF100** [diamondburned/gtkcord4#78]
I am not familiar with go, but is there a way to instruct the compiler to use all available threads to compile? By default, `go build` only uses a single core to compile, which makes it take absolutely ages to finish...

**Comment by Phoenix-Starlight** [comment]
``go build -p n``? This determines how many build commands or tests can be run in parallel. This is set to how many CPUs are available by default by`` GOMAXPROCS``

**Comment by diamondburned** [comment]
cmd/cgo won't be parallel. See https://github.com/golang/go/issues/9887. I can't really do much other than to tell you to use the patchsets (which are already in gotk4-nix).
