### ISSUE TITLE
Automate project compilation thanks to GitHub Actions

### ISSUE THREAD

**Issue by DodoLeDev** [diamondburned/gtkcord4#81]
Hi!
Because several people complain that the build time is too long, why don't you automate the build process with GitHub Actions? 😃
It would save a lot of time for everyone, including you, and you can even make it build a libadwaita version, without problems!

More info can be found here: [Building and testing Go](https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go)

**Comment by diamondburned** [comment]
GitHub Actions has nothing to do with build times.

This repository already has release automations: https://builds.sr.ht/~diamondburned/job/870018.

**Comment by diamondburned** [comment]
The binaries can be found in the Releases page: https://github.com/diamondburned/gtkcord4/releases/tag/v0.0.5.
