### ISSUE TITLE
./gtkcord4: not found

### ISSUE THREAD

**Issue by TheKrafter** [diamondburned/gtkcord4#82]
On postmarketOS (Alpine-based) and downloaded v0.0.5 from the releases page. gave the archive a good ol' `tar -xvf` aaaaannd...
```
/usr/bin/ash: ./gtkcord4: not found
```
the file IS there, (`ls`, TAB autocomplete, and a GUI package manager (nautilus) both prove it's there). Neither `chmod +x`, nor `chown` yield any results. This is the same error given when a random file is called. I have not been able to compile from source, even though satisfying all dependencies.

**Comment by diamondburned** [comment]
The CI-built binary will need glibc. You should either build this yourself or try and install a glibc-compat utility.

The CI can be configured to build using muslc, however the Nixpkgs version of that doesn't seem to work for me.
