### ISSUE TITLE
Feature request: image previews

### ISSUE THREAD

**Issue by TriVoxel** [diamondburned/gtkcord4#85]
Hey, great work on this application. I needed to manually set a [GTK theme that supports GTK4](https://github.com/ronny-rentner/adwaita-gtk3-gtk4-theme) and then enable it in Gnome Tweaks to get the dark theme working, but it was easy and your app looks fantastic! It feels very polished, and only seems to be missing a few things that would bring it very much in line with Discord itself. Very impressive!

As Discord is a great service for sharing images and videos, I think it would be awesome if images would open as a preview in a dedicated window as opposed to opening in the browser. Either a popup like Discord does, or even a separate image or video viewer would really improve the chat a lot, and make the app more cohesive.

Personally, I think a simple popup window would be good, and you can press X to close it, maybe right click to copy or save image.

Example:
![Screenshot from 2022-11-19 01-04-11](https://user-images.githubusercontent.com/25536957/202841295-7d57696f-6ff5-444c-b69a-6c06ec99a41b.png)

**Comment by diamondburned** [comment]
I have the code for this somewhere in one of my 50 UI-related project folders... It's half-way done, but it would be great if I know where that is...

**Comment by diamondburned** [comment]
I found it.

![image](https://user-images.githubusercontent.com/8463786/202843473-04d80d01-1fa4-431a-824e-2598d4fa90f1.png)

I'm not sure how usable this is at the moment, so I'm not ready to add it into gtkcord4 yet. The code is public, though: [embed.Viewer](https://pkg.go.dev/github.com/diamondburned/chatkit@v0.0.0-20221018050103-b0594151c699/components/embed#Viewer).

**Comment by TriVoxel** [comment]
Looks fantastic; would love to see it when it's finished! Definitely something worth announcing.

**Comment by tfuxu** [comment]
@diamondburned 
How did you got `embed.Viewer` to display anything? I've tried creating a new viewer dialog in `image.SetOpenURL`, but it always displays an empty embed

#### Here's an code snippet:
```go
image.SetOpenURL(func() {
	embedViewer := NewViewer(ctx, opts)
	embedViewer.Show()
})
```

#### Screenshot:
![Screenshot from 2023-10-29 19-10-39](https://github.com/diamondburned/gtkcord4/assets/73042332/93eceeb0-19c7-4dc1-b669-fa0b7077727f)

**Comment by diamondburned** [comment]
`embedViewer` gets an `Embed` field that you can use to change the image. The API is not nearly as intuitive as I wanted it to be, and I've last touched this code like a year ago at least.

**Comment by tfuxu** [comment]
> `embedViewer` gets an `Embed` field that you can use to change the image. The API is not nearly as intuitive as I wanted it to be, and I've last touched this code like a year ago at least.

I'll see what can be done, it would be cool to make it more generic (i.e. add support for displaying local images), to allow more range of apps to use it too.

**Comment by diamondburned** [comment]
> it would be also cool to make it more generic (i.e. add support for displaying local images), to allow more range of apps to use it too

It technically already does! `onlineimage` can display local images with the `file://` URI. In fact, it supports *anything* given the right `Provider`.

**Comment by tfuxu** [comment]
Got it working, now I just need to fix this weird embed centering, and after that the main part of viewer should be ready to use.

![Screenshot from 2023-10-30 21-37-14](https://github.com/diamondburned/gtkcord4/assets/73042332/2d07d7a0-cde9-4ea9-9a3d-760c60b90465)
![Screenshot from 2023-10-30 21-41-39](https://github.com/diamondburned/gtkcord4/assets/73042332/a2e87204-637c-4bd0-99e3-50a7a88ad144)

**Comment by diamondburned** [comment]
Could you check that these things work?

- Panning using two-finger touchpad
- Zooming using two-finger touchpad
- Panning by dragging mouse
- Zooming by scrolling mouse

I would consider these fairly essential features for a working image viewer.

**Comment by diamondburned** [comment]
(Wouldn't it be cool if `eog` is available as a library?)

**Comment by tfuxu** [comment]
Panning and zooming works with mouse, I'll test tomorrow if it also works with touchpads.

> (Wouldn't it be cool if `eog` is available as a library?)

For real, especially `loupe` with its `glycin` library would be amazing for embedding in libadwaita apps

**Comment by tfuxu** [comment]
Also, here's an updated look to viewer:
![Screenshot from 2023-10-30 23-37-49](https://github.com/diamondburned/gtkcord4/assets/73042332/8e3985d0-0901-4530-b4fb-9c197fdacbb9)

I'll probably also add buttons for zooming and full screening later

**Comment by diamondburned** [comment]
Do you think it is possible to, for now, disable zooming and panning? Then we can release it for now.

**Comment by tfuxu** [comment]
I'm back. I think everything should be now done, I've added code for download button, switched from `gtk.Dialog` and popovers to `adw.Window` and toasts, and polished the UI a little bit.

Here's the final look:

![Screenshot from 2023-11-04 00-11-17](https://github.com/diamondburned/gtkcord4/assets/73042332/a8e58876-fcb5-445d-9bc7-5fa9297781f1)

I've also removed zooming, as the current implementation caused severe memory leaks if zoomed too much. 

From what I've checked in Loupe and EOG, a proper zoom backend should be done using tiles, which involves using an external image processing library and making custom widgets, so probably a little too much for a simple embeddable image viewer.

**Comment by diamondburned** [comment]
> From what I've checked in Loupe and EOG, a proper zoom backend should be done using tiles, which involves using an external image processing library and making custom widgets

That's understandable. Making a custom widget is unfortunately not possible right now :( 

(I blame GLib for that.)

Does the current implementation cause any memory leaks at all?
