### ISSUE TITLE
Preferences menu?

### ISSUE THREAD

**Issue by SilverMarcs** [diamondburned/gtkcord4#9]
Is there a hidden menu for options? If not, how do you change theme?

**Comment by diamondburned** [comment]
There is a preferences menu that's hidden at the moment (since there's no button for it yet), but it doesn't have an option to change GTK theme.

gtkcord4 uses your system's GTK theme, so you'd change it according to however you'd change it on your system.

**Comment by SilverMarcs** [comment]
Okay ya it works like that. The theme I was using didnt include css for gtk4 themes so it wasnt being followed.

**Comment by diamondburned** [comment]
Actually, I'm keeping this open until the button is added.

**Comment by diamondburned** [comment]
Replacing this issue with #30.
