### ISSUE TITLE
User stylesheets?

### ISSUE THREAD

**Issue by DodoLeDev** [diamondburned/gtkcord4#91]
Hi!
In order to debug something with my current gtkcord installation, during the initialization process, I was faced with this message: :thinking:
![Debug output screenshot](https://user-images.githubusercontent.com/59477313/202866094-84fa423c-0aa2-4e15-aeae-d7c93b8b2216.png)

So I'm asking this question: _do you have any plans to add user-defined stylesheets in GTKcord, and if yes, how could I take advantage of it?_

I'm so excited to see this feature completely implemented in a future release! :star_struck: 

Best regards!

**Comment by diamondburned** [comment]
> So I'm asking this question: _do you have any plans to add user-defined stylesheets in GTKcord, and if yes, how could I take advantage of it?_

It's already added. Just make a file at the path that it's complaining about and you're good.

To fully utilize the stylesheets, I recommend using the Inspector UI (<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>I</kbd>). Use the existing class names as the selectors.
