### ISSUE TITLE
captcha error

### ISSUE THREAD

**Issue by justdie386** [diamondburned/gtkcord4#93]
└ Failed to login:
    └ Discord returned status 400 body {"captcha_key":
        └ ["captcha-required"], "captcha_sitekey":
            └ "f5561ba9-8f1e-40ca-9b5b-a0b3f719ef34", "captcha_service":
                └ "hcaptcha"}.

**Comment by justdie386** [comment]
Also, how am i supposed to use 2fa?

**Comment by diamondburned** [comment]
Don't use the regular login. Use the token login.

**Comment by guglovich** [comment]
If only the instructions were directly on the project page. Now I'm looking for a way to get it myself.

**Comment by diamondburned** [comment]
See gtkcord3's: https://github.com/diamondburned/gtkcord3#logging-in

**Comment by Bitals** [comment]
@diamondburned they are not relevant anymore, at least for me.

What worked:
1. Open Discord Login Page in a browser;
2. Enter your creds;
3. Filter Network tab by "login";
4. Go to the captured request, switch to response;
5. Copy the "token" field from response

**Comment by diamondburned** [comment]
Searching for `discord api` will work. There's no need to re-login.

**Comment by Bitals** [comment]
> Searching for discord api will work.
Well that got me a token, but it was not the full one. Weirdly most requests I checked had this cut one containing roughly 2/3 of the Login token.

**Comment by diamondburned** [comment]
> Well that got me a token, but it was not the full one

You might've clicked the wrong request. Any request that goes to `discord.com/api/v9` should work. They all give me the same token that I always use.

**Comment by diamondburned** [comment]
I added token instructions into the README.
